In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('Mall_Customers.csv')


In [3]:
dataset

CustomerID   Genre  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
1             2    Male   21                  15                      81
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
..          ...     ...  ...                 ...                     ...
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

[200 rows x 5 columns]

In [4]:
X = dataset.iloc[:, [3, 4]].values

In [ ]:
from sklearn.cluster import KMeans
wcss = []
for i in range(1, 11):
    kmeans = KMeans(n_clusters = i, init = 'k-means++', random_state = 42)
    kmeans.fit(X)
    wcss.append(kmeans.inertia_)
plt.plot(range(1, 11), wcss)
plt.title('The Elbow Method')
plt.xlabel('Number of clusters')
plt.ylabel('WCSS')
plt.show()

In [5]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters = 5, init = 'k-means++', random_state = 42)
y_kmeans = kmeans.fit_predict(X)

In [ ]:
y_kmeans

In [6]:
supervised1=pd.DataFrame(dataset)

In [7]:
supervised1['Cluster_group']=y_kmeans

In [ ]:
supervised1.to_csv("cluster.csv",index=False)

In [ ]:
centroids=kmeans.cluster_centers_

In [ ]:
centroids

In [ ]:
y_kmeans

In [ ]:
import seaborn as sns
facet = sns.lmplot(data=supervised, x=supervised.columns[3], y=supervised.columns[4], hue=supervised.columns[5], 
                   fit_reg=False, legend=True, legend_out=True)

In [9]:
from sklearn.cluster import AgglomerativeClustering
clusmodel = AgglomerativeClustering(n_clusters = 5)
label = clusmodel.fit_predict(X)
supervised=pd.DataFrame(dataset)
supervised['Cluster_group']=label

In [10]:
df=pd.DataFrame()

In [11]:
df["kmeans"]=supervised1['Cluster_group']
df["Agglo"]=supervised['Cluster_group']

In [12]:
df

kmeans  Agglo
0         4      4
1         3      3
2         4      4
3         3      3
4         4      4
..      ...    ...
195       2      2
196       0      0
197       2      2
198       0      0
199       2      2

[200 rows x 2 columns]

In [14]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(df["kmeans"], df["Agglo"])


In [16]:
print(cm)

[[32  0  0  0  0]
 [ 0 85  0  0  0]
 [ 0  0 39  0  0]
 [ 0  0  0 21  0]
 [ 0  0  0  0 23]]


In [17]:
from sklearn.metrics import classification_report
clf_report = classification_report(df["kmeans"], df["Agglo"])

In [19]:
print(clf_report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        32
           1       1.00      1.00      1.00        85
           2       1.00      1.00      1.00        39
           3       1.00      1.00      1.00        21
           4       1.00      1.00      1.00        23

    accuracy                           1.00       200
   macro avg       1.00      1.00      1.00       200
weighted avg       1.00      1.00      1.00       200

